# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["172.31.41.154:9090"]

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8080']

#  - job_name: 'authentication-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ '172.31.41.154:8095' ]

  - job_name: 'chat-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8099' ]

#  - job_name: 'email-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ '172.31.41.154:587' ]

  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:

      - targets: [ '172.31.41.154:8761' ]

#  - job_name: 'payment-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ '172.31.41.154:8065' ]

  - job_name: 'product-recommendation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8070' ]

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8097' ]

  - job_name: 'product-trading-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8075' ]

#  - job_name: 'qr-generate-service'
#    metrics_path: '/actuator/prometheus'
#    scrape_interval: 3s
#    static_configs:
#      - targets: [ '172.31.41.154:8066' ]


  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ '172.31.41.154:8090' ]
