FROM openjdk
WORKDIR user/lib
ADD ./target/product-trading-service-0.0.1-SNAPSHOT.jar /user/lib/product-trading-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","product-trading-service-0.0.1-SNAPSHOT.jar"]